### PR TITLE
feat: added transactions tab

### PR DESCRIPTION
**Pull request by sadiqasg**
Added transactions component on dashboard

### CODE REVIEW

**Review by iyosayi — CHANGES_REQUESTED** [review]
The "buy", "sell" and "broker" buttons should be replaced with the "Create Transaction" button.
In the dashboard overview, the card that displays 'hello *username* should be replaced with "Create transaction"

**Comment by sadiqasg** [comment]
@iyosayi the PR has been updated

**Review by iyosayi — CHANGES_REQUESTED** [review]
The transactions table should be replaced with the card layout

**Comment by sadiqasg** [comment]
hi, @iyosayi please check the transaction page modifications

**Review by iyosayi — CHANGES_REQUESTED** [review]
The `Status button` should be removed, as the status will just be displayed in plain text, for example `Status - Awaiting Confirmation`. The `View Details button` should be a mini dropdown where you can just see an overview of the transaction. For example, 
When I click the `View details` button, I should see 
- I should see the `Amount` tied to the transaction.
- The `reference number` of the transaction
- The recipient's `email and ID`
- The `transaction status`

**Comment by sadiqasg** [comment]
hello @iyosayi , check the updated PR

**Comment by iyosayi** [comment]
Okay, it works.

**Pull request merged**
